---

- name: Package YUM - Install 'epel-release'
  yum:
    name: "epel-release"
    state: "{{ 'absent' if not package_yum_epel else 'present' }}"
  when: package_yum_epel | bool

- name: Package YUM - Custom Repo
  yum_repository:
    name: "{{ item.name | lower }}"
    description: "{{ item.name }}"
    file: "{{ item.filename | lower | default(item.name) }}"
    baseurl: "{{ item.baseurl }}"
    gpgcakey: "{{ item.gpgcakey }}"
    gpgcheck: "{{ item.gpgcheck | default('no') }}"
    enabled: "{{ item.enable | default('yes') }}"
    state: "{{ item.state | default(package_state) }}"
  when: item.state|default('present')
  with_items: "{{ package_yum_repo_custom }}"
  notify: YUM Clean Metadata

- name: Package YUM - Install packages
  yum:
    name: "{{ package_list_install.yum }}"
    state: present
    update_cache: "{{ package_update_cache }}"

- name: Package YUM - Remove packages
  yum:
    name: "{{ package_list_remove.yum }}"
    state: absent
    update_cache: "{{ package_update_cache }}"
